### ISSUE TITLE
 Inquiry on Runtime and GPU Usage

### ISSUE THREAD

**Issue by sitaharsha** [instadeepai/selective-reincarnation-marl#1]
Hello instadeepai,

I have a couple of questions regarding the usage of your package. Specifically, I'm trying to run the `python experiments/default_exp.py` command on a 64 core system, and I'm curious about the expected runtime for this command. Could you please provide me with an estimate or range of expected runtimes for this command?

Additionally, I noticed that the command does not seem to be utilizing GPU. I wanted to confirm if this is expected behavior, or if there are any changes I need to make to the configuration to enable GPU usage. Any guidance or suggestions you can provide would be greatly appreciated.

Thank you very much for your time and assistance.

**Comment by sitaharsha** [comment]
Based on my experience, the expected runtime for this command on a 64-core system should be around four hours. However, the actual runtime may vary depending on the system configuration and other factors. But I am still unsure about the GPU usage.

**Comment by jcformanek** [comment]
Hi there, we found that using a GPU made the experiments slower. Using a GPU only helped when the Networks were made larger. I think it is fairly common in RL for a GPU not to be that useful. That is why we default to using CPU only. About 4 hours is the same as what it took us to run an experiment.
